# Generated by Django 3.0.9 on 2020-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect360', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address_1', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
